### ISSUE TITLE
No Audio output from my speakers

### ISSUE THREAD

**Issue by jonneymendoza** [pop-os/system76-driver#168]
**Distribution (run `cat /etc/os-release`):**
 
 ```NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Chrome youtube, spotify

**Issue/Bug Description:**

Hi i am getting no sound at all from my speakers that are connected to a line-out connector on my desktop computer. Same setup works fine on when i dual boot to windows 10.

Here is my hardware specs:
```
- AMD Ryzen Threadripper 3960X 24-Core Processor
- 128gb ddr4 ram
- Asus ROG ZENITH 2 EXTREME Motherboard
- M.2 4Tb SSD DRIVE.
- NVIDIA 2080TI Gpu
- Pop OS 20.10
- ASUS PA32UC-K 32 Inch Professional Monitor
```

The audio only works through the headphone jack of my desktop or through my 4k monitor display connected via displayPort.

I tried following the guide/troubleshoot here https://support.system76.com/articles/audio/ and installed pulseAudio volume controler and tried to manually select the line-out output and still no sound is coming out of it

**Steps to reproduce (if you know):**
Play any media with sound output  from chrome or spotify or any other program that outputs sound

**Expected behavior:**
Play the sound through my line-out connected speakers

**Other Notes:**
Works if i set the audio output to my 4k monitor speakers or the headphone jack connected to my computer destop

My alsa-info http://alsa-project.org/db/?f=ad7926a7f5fd307d7484fcfb600f7c0d0b6df446 

**List of audio devices in my computer:**

```23:00.1 Audio device: NVIDIA Corporation TU102 High Definition Audio Controller (rev a1)
	Subsystem: NVIDIA Corporation TU102 High Definition Audio Controller
	Flags: bus master, fast devsel, latency 0, IRQ 159, IOMMU group 28
	Memory at e1080000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

--
25:00.4 Audio device: Advanced Micro Devices, Inc. [AMD] Starship/Matisse HD Audio Controller
	Subsystem: ASUSTeK Computer Inc. Starship/Matisse HD Audio Controller
	Flags: fast devsel, IRQ 255, IOMMU group 33
	Memory at e1400000 (32-bit, non-prefetchable) [disabled] [size=32K]
	Capabilities: <access denied>
	Kernel modules: snd_hda_intel

```

**Comment by jacobgkau** [comment]
> Hi i am getting no sound at all from my speakers that are connected to a line-out connector on my desktop computer. Same setup works fine on when i dual boot to windows 10.
> 
> Here is my hardware specs:

Hello. Are you using a System76 desktop, or some other desktop? We don't use the ZENITH II EXTREME in any of our machines to my knowledge, so I'm not sure the `system76-driver` repository is the correct repository for this issue, since `system76-driver` is meant to support System76 hardware.

Does the same issue occur if you boot a live disk of vanilla Ubuntu? I know we sometimes do work on the motherboards we use to get audio working correctly, and since we don't use that motherboard, it's possible nobody has done that work yet. That would likely need to be fixed in the Linux kernel itself by someone who is able to develop drivers for that motherboard.

If this is a System76 product, please open a [support case](https://support.system76.com/) so our support team can get some logs and figure out where the issue lies.

**Comment by crawfxrd** [comment]
This is not System76 hardware.
